### ISSUE TITLE
Helm install fails due to ingress annotation in default values file

### ISSUE THREAD

**Issue by cascadia-sati** [ToolJet/helm-charts#43]
Installing the Helm chart to fail with this error:

```
Error: INSTALLATION FAILED: 1 error occurred:
	* Ingress.networking.k8s.io "tooljet" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: "nginx": can not be set when the class field is also set
```

Because the default values file contains an `kubernetes.io/ingress.class` annotation that conflicts with `ingressClassName`:

```
ingress:
  enabled: true
  hostname: tooljet.localhost
  ingressClassName: 'nginx'
  annotations:
    kubernetes.io/ingress.class: "nginx".   <---- BAD!
  tls: []
```

Annoyingly, setting other annotations in the customs value file doesn't fix this, since this default one is merged. It has to be explicitly unset, like in ours where we set a cert-manager annotation:

```
ingress:
  enabled: true
  hostname: tooljet.localhost
  ingressClassName: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    kubernetes.io/ingress.class:      <---- UNSET!
  tls: []
```
